name: GomGrow
version: 1.0.0
main: me.dolphin2410.gomgrow.GomGrow
author: dolphin2410
api-version: 1.19
libraries:
  - io.github.monun:tap-core:4.8.0
  - io.github.monun:kommand-core:2.14.0
  - io.github.monun:invfx-core:3.2.0
